
project_id = "cdoulaabovfxrjzjowtw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
jwt_expiry = 3600

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.integration-template]
verify_jwt = true
