// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdoulaabovfxrjzjowtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkb3VsYWFib3ZmeHJqempvd3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTY4NDQsImV4cCI6MjA2Mjk5Mjg0NH0.TE2KvePGV3XaUHjOule8sUfbDrxqZpFT9HI-zCsWH6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);